source 'http://rubygems.org'

gem "compass", "1.0.1"
gem "susy", "2.1.3"
gem "breakpoint"
gem "haml"
gem "sass", "3.4.9"
gem "nanoc", "3.7.4"
gem "RedCloth"
gem "redcarpet"
gem "builder"
gem "adsf"
gem "nokogiri"
gem "pygments.rb", "0.6.0"
gem "guard"
gem "guard-coffeescript"
gem "guard-nanoc"
gem "guard-rspec"
